# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: '6bd06657-2155-4af5-9d6a-8fc06361ed75'
  appName: 'mncd'

stages:
- stage: build
  jobs:
    - job: build_job
      steps:
        - script: cd src
          displayName: 'Move to src directory'
        - script: dotnet build --configuration $(buildConfiguration)
          displayName: 'dotnet build $(buildConfiguration)'

- stage: deploy
  jobs:
    - job: deploy_job
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: publish
            publishWebProjects: True
            arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
            zipAfterPublish: True

        - task: PublishBuildArtifacts@1
          inputs:
            pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
            artifactName: 'myWebsiteName'

        - task: AzureWebApp@1
          inputs:
            azureSubscription: $(azureSubscription)
            appType: webAppLinux
            appName: $(appName)
            package: $(System.ArtifactsDirectory)/**/*.zip